services:

  transaction-dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    container_name: transaction-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/transactionServer
    tty: true
    links:
      - postgres
    environment:
    - CONFIG_FILE=/transactionServer/bench-config.toml
    - DB_USER=postgres
    - DB_NAME=transactions-db

  postgres:
    image: postgres:alpine3.20
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=transactions-db
